<a href="https://colab.research.google.com/github/yujungha/AI-Study/blob/main/7_2%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X1 = 1
X2 = 2

Y1 = 2
Y2 = 1

a = 0.1

W11 = 0.1
W12 = 0.2
W21 = 0.3
W22 = 0.1

O1 = X1 * W11 + X2 * W21
O2 = X1 * W12 + X2 * W22

E1 = (Y1 - O1)**2
E2 = (Y2 - O2)**2

print(O1, O2)
print(E1, E2)

dE1dW11 = -2 * (Y1 - O1) * X1
dE1dW21 = -2 * (Y1 - O1) * X2
dE2dW12 = -2 * (Y2 - O2) * X1
dE2dW22 = -2 * (Y2 - O2) * X2

W11 = W11 - a * dE1dW11
W21 = W21 - a * dE1dW21
W12 = W12 - a * dE2dW12
W22 = W22 - a * dE2dW22

print(np.array([[dE1dW11, dE2dW12],
                [dE1dW21, dE2dW22]]))

O1 = X1 * W11 + X2 * W21
O2 = X1 * W12 + X2 * W22

E1 = (Y1 - O1)**2
E2 = (Y2 - O2)**2

print(O1, O2)
print(E1, E2)

0.7 0.4
1.6900000000000002 0.36
[[-2.6 -1.2]
 [-5.2 -2.4]]
2.0 1.0
0.0 0.0


In [ ]:
X = np.array([[1, 2]])
Y = np.array([[2, 1]])
W = np.array([[0.1, 0.2],
              [0.3, 0.1]])
O = X.dot(W)
print(O)
E = (Y - O)**2
print(E)

[[0.7 0.4]]
[[1.69 0.36]]


In [138]:
X = np.array([[1, 3]])
Y = np.array([[3]])
W = np.array([[0.2],
              [0.4]])

a = 0.01
epoch = 10
for i in range(epoch):
  O = X.dot(W)
  E = (Y - O)**2
  # print(O)
  # print(E)

  dEdW = -2 * (Y - O) * X.T

  W = W - a * dEdW
  print(W)

  O = X.dot(W)
  E = (Y - O)**2
  print(O)
  print(E)

[[0.232]
 [0.496]]
[[1.72]]
[[1.6384]]
[[0.2576]
 [0.5728]]
[[1.976]]
[[1.048576]]
[[0.27808]
 [0.63424]]
[[2.1808]]
[[0.67108864]]
[[0.294464]
 [0.683392]]
[[2.34464]]
[[0.42949673]]
[[0.3075712]
 [0.7227136]]
[[2.475712]]
[[0.27487791]]
[[0.31805696]
 [0.75417088]]
[[2.5805696]]
[[0.17592186]]
[[0.32644557]
 [0.7793367 ]]
[[2.66445568]]
[[0.11258999]]
[[0.33315645]
 [0.79946936]]
[[2.73156454]]
[[0.07205759]]
[[0.33852516]
 [0.81557549]]
[[2.78525164]]
[[0.04611686]]
[[0.34282013]
 [0.82846039]]
[[2.82820131]]
[[0.02951479]]


In [ ]:
train_x = np.array([[1,3]])
train_y = np.array([[3]])

for j in range(1):
    X = np.array([train_x[j]])
    Y = np.array([train_y[j]])
    W = np.random.rand(2,1)
    a = 0.01

    for i in range(50):
        print('========step'+str(i)+'========')
        O = X.dot(W)
        print('output :', O[0])
        E = (Y - O)**2
        print('error :',E.sum())
        # print(X)
        dEdW = -2 * (Y - O) * X.T
        W = W - a * dEdW

In [144]:
# 2 x 1

train_x = np.array([[1, 3]])
train_y = np.array([[3]])

for j in range(1):
    X = np.array([train_x[j]])
    Y = np.array([train_y[j]])
    W = np.random.rand(2,1)
    a = 0.01

    for i in range(50):
        print('========step'+str(i)+'========')
        O = X.dot(W)
        print('output :', O[0])
        E = (Y - O)**2
        print('error :',E.sum())
        # print(X)
        dEdW = -2 * (Y - O) * X.T
        W = W - a * dEdW

========step0========
output : [3.36708936]
error : 0.13475459579964538
========step1========
output : [3.29367149]
error : 0.0862429413117732
========step2========
output : [3.23493719]
error : 0.05519548243953468
========step3========
output : [3.18794975]
error : 0.03532510876130229
========step4========
output : [3.1503598]
error : 0.022608069607233522
========step5========
output : [3.12028784]
error : 0.014469164548629326
========step6========
output : [3.09623027]
error : 0.009260265311122838
========step7========
output : [3.07698422]
error : 0.005926569799118643
========step8========
output : [3.06158737]
error : 0.0037930046714359533
========step9========
output : [3.0492699]
error : 0.0024275229897190013
========step10========
output : [3.03941592]
error : 0.001553614713420175
========step11========
output : [3.03153274]
error : 0.0009943134165889007
========step12========
output : [3.02522619]
error : 0.000636360586616901
========step13========
output : [3.02018095]
error :

In [149]:
# 2 x 3

train_x = np.array([[2, 4]])
train_y = np.array([[1, 3, 5]])

for j in range(1):
    X = np.array([train_x[j]])
    Y = np.array([train_y[j]])
    W = np.random.rand(2, 3)
    a = 0.01

    for i in range(50):
        print('========step'+str(i)+'========')
        O = X.dot(W)
        print('output :', O[0])
        E = (Y - O)**2
        print('error :',E.sum())
        # print(X)
        dEdW = -2 * (Y - O) * X.T
        W = W - a * dEdW

========step0========
output : [2.18554281 1.26414997 2.81209108]
error : 9.20563252835223
========step1========
output : [1.71132569 1.95848998 3.68725465]
error : 3.314027710206802
========step2========
output : [1.42679541 2.37509399 4.21235279]
error : 1.1930499756744481
========step3========
output : [1.25607725 2.62505639 4.52741167]
error : 0.42949799124280125
========step4========
output : [1.15364635 2.77503384 4.716447  ]
error : 0.15461927684740814
========step5========
output : [1.09218781 2.8650203  4.8298682 ]
error : 0.05566293966506725
========step6========
output : [1.05531269 2.91901218 4.89792092]
error : 0.02003865827942416
========step7========
output : [1.03318761 2.95140731 4.93875255]
error : 0.007213916980592662
========step8========
output : [1.01991257 2.97084439 4.96325153]
error : 0.002597010113013317
========step9========
output : [1.01194754 2.98250663 4.97795092]
error : 0.0009349236406848135
========step10========
output : [1.00716852 2.98950398 4.98677