<a href="https://colab.research.google.com/github/yujungha/AI-Study/blob/main/7_2%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
X1 = 1
X2 = 2

Y1 = 2
Y2 = 1

a = 0.1

W11 = 0.1
W12 = 0.2
W21 = 0.3
W22 = 0.1

O1 = X1 * W11 + X2 * W21
O2 = X1 * W12 + X2 * W22

E1 = (Y1 - O1)**2
E2 = (Y2 - O2)**2

print(O1, O2)
print(E1, E2)

dE1dW11 = -2 * (Y1 - O1) * X1
dE1dW21 = -2 * (Y1 - O1) * X2
dE2dW12 = -2 * (Y2 - O2) * X1
dE2dW22 = -2 * (Y2 - O2) * X2

W11 = W11 - a * dE1dW11
W21 = W21 - a * dE1dW21
W12 = W12 - a * dE2dW12
W22 = W22 - a * dE2dW22

print(np.array([[dE1dW11, dE2dW12],
                [dE1dW21, dE2dW22]]))

O1 = X1 * W11 + X2 * W21
O2 = X1 * W12 + X2 * W22

E1 = (Y1 - O1)**2
E2 = (Y2 - O2)**2

print(O1, O2)
print(E1, E2)

0.7 0.4
1.6900000000000002 0.36
[[-2.6 -1.2]
 [-5.2 -2.4]]
2.0 1.0
0.0 0.0


In [8]:
X = np.array([[1, 2]])
Y = np.array([[2, 1]])
W = np.array([[0.1, 0.2],
              [0.3, 0.1]])
O = X.dot(W)
print(O)
E = (Y - O)**2
print(E)

[[0.7 0.4]]
[[1.69 0.36]]
