<a href="https://colab.research.google.com/github/yujungha/AI-Study/blob/main/9_2%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.optim as optim
import torch.nn as nn

In [ ]:
df = pd.read_csv('train.csv')
df2 = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']].reset_index()

df2.loc[:,'Sex'] = df2.loc[:,'Sex'].str.replace('female', '0')
df2.loc[:,'Sex'] = df2.loc[:,'Sex'].str.replace('male', '1')
df2['Sex'] = df2['Sex'].astype(int)
df2['Pclass'] = round(df2['Pclass'] / 3, 1)
df2['Age'] = round(df2['Age'] / 80 , 1)
df2 = df2.dropna(subset=['Age'])
df2['Fare'] = round(df2['Fare'] / df2['Fare'].max() , 3)
df3 = df2['Survived'].head().values
df3 = [[x] for x in df3]
del df2['index']
del df2['Survived']

x_train = torch.FloatTensor(df2.head().values)
y_train = torch.FloatTensor(df3)

model = nn.Sequential(
    nn.Linear(4, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

learning_rate = 0.02
epochs = 10000

optimizer = optim.Adam(model.parameters(), lr=learning_rate)
cost = nn.MSELoss()

for i in range(epochs + 1):
  y = model(x_train)
  loss = cost(y, y_train)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if i % 1000 == 0:
    print(i, loss.item())

print(model(x_train))

0 0.5029163956642151
1000 1.3080169082968496e-05
2000 4.411121246050698e-09
3000 5.777600891199858e-14
4000 2.612541259716661e-11
5000 8.074800462054554e-06
6000 5.615417464355232e-09
7000 3.560887762432685e-06
8000 9.555600755106752e-10
9000 0.0
10000 0.0
tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.]], grad_fn=<AddmmBackward>)


In [ ]:
df = pd.read_csv('train.csv')
df2 = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']].reset_index()

df2.loc[:,'Sex'] = df2.loc[:,'Sex'].str.replace('female', '0')
df2.loc[:,'Sex'] = df2.loc[:,'Sex'].str.replace('male', '1')
df2['Sex'] = df2['Sex'].astype(int)
df2['Pclass'] = round(df2['Pclass'] / 3, 1)
df2['Age'] = round(df2['Age'] / 80 , 1)
df2 = df2.dropna(subset=['Age'])
df2['Fare'] = round(df2['Fare'] / df2['Fare'].max() , 3)
df3 = df2['Survived'].values
df3 = [[x] for x in df3]
del df2['index']
del df2['Survived']

x_train = torch.FloatTensor(df2.values)
y_train = torch.FloatTensor(df3)

model = nn.Sequential(
    nn.Linear(4, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

learning_rate = 0.01
epochs = 10000

optimizer = optim.Adam(model.parameters(), lr=learning_rate)
cost = nn.MSELoss()

for i in range(epochs + 1):
  y = model(x_train)
  loss = cost(y, y_train)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if i % 1000 == 0:
    output = torch.abs(torch.round(model(x_train)))
    print(i, loss.item(), '%.2f%%'%((y_train == output).float().mean().numpy() * 100))

0 0.5415535569190979 59.38%
1000 0.09538930654525757 87.96%
2000 0.08877456933259964 88.52%
3000 0.07861620932817459 89.92%
4000 0.07276275008916855 90.76%
5000 0.06602360308170319 90.76%
6000 0.07021220773458481 91.04%
7000 0.06427787244319916 91.46%
8000 0.06796039640903473 91.32%
9000 0.07403182238340378 90.62%
10000 0.09004572778940201 88.80%


In [ ]:
output = torch.abs(torch.round(model(x_train)))
print('%.2f%%'%((y_train == output).float().mean().numpy() * 100))

87.68%


In [ ]:
print()

tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
      

In [ ]:
df2.head().values

array([[1.   , 1.   , 0.3  , 0.014],
       [0.3  , 0.   , 0.5  , 0.139],
       [1.   , 0.   , 0.3  , 0.015],
       [0.3  , 0.   , 0.4  , 0.104],
       [1.   , 1.   , 0.4  , 0.016]])

In [ ]:
df3

[[0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [1]